<?php
return array (
  'wlm3u8' => 
  array (
    'status' => '1',
    'from' => 'wlm3u8',
    'show' => 'wlm3u8',
    'des' => 'https://wlzy.tv',
    'ps' => '1',
    'parse' => 'https://jx.inpower.cc/?url=',
    'sort' => '999',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'wlm3u8',
  ),
  'subom3u8' => 
  array (
    'status' => '1',
    'from' => 'subom3u8',
    'show' => '速播在线',
    'des' => '支持手机电脑在线播放',
    'ps' => '0',
    'parse' => '',
    'sort' => '994',
    'tip' => '无需安装任何插件',
    'id' => 'subom3u8',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'sort' => '908',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'sort' => '906',
    'from' => 'iva',
    'show' => 'H5自带解析',
    'des' => 'videojj.com',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'real' => 
  array (
    'status' => '1',
    'sort' => '902',
    'from' => 'real',
    'show' => 'RealPlaer播放器',
    'des' => 'real.cn',
    'parse' => '',
    'ps' => '0',
    'tip' => '需要电脑安装RealPlayer播放器',
    'id' => 'real',
  ),
  'media' => 
  array (
    'status' => '1',
    'sort' => '901',
    'from' => 'media',
    'show' => 'MediaPlayer播放器',
    'des' => 'mediaplayer',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'media',
  ),
  'xigua' => 
  array (
    'status' => '0',
    'from' => 'xigua',
    'show' => '西瓜影音',
    'des' => 'xigua.com',
    'ps' => '0',
    'parse' => '',
    'sort' => '712',
    'tip' => '<a href="//union.maccms.com/html/xigua.html" target="_blank">需要下载西瓜影音播放器</a>',
    'id' => 'xigua',
  ),
  'xfplay' => 
  array (
    'status' => '0',
    'sort' => '711',
    'from' => 'xfplay',
    'show' => '先锋影音',
    'des' => 'xfplay.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/xfplay.html" target="_blank">需要下载先锋影音播放器</a>',
    'id' => 'xfplay',
  ),
  'jjvod' => 
  array (
    'status' => '0',
    'sort' => '710',
    'from' => 'jjvod',
    'show' => '吉吉影音',
    'des' => 'jijizy.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/jjvod.html" target="_blank">需要下载吉吉影音播放器</a>',
    'id' => 'jjvod',
  ),
  'fvod' => 
  array (
    'status' => '0',
    'sort' => '709',
    'from' => 'fvod',
    'show' => '肥佬影音',
    'des' => 'www.feilao.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/fvod.html" target="_blank">需要下载肥佬影音播放器</a>',
    'id' => 'fvod',
  ),
  'ffhd' => 
  array (
    'status' => '0',
    'sort' => '708',
    'from' => 'ffhd',
    'show' => '非凡影音',
    'des' => 'www.feifan.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/ffhd.html" target="_blank">需要下载非凡影音播放器</a>',
    'id' => 'ffhd',
  ),
  'niba' => 
  array (
    'status' => '0',
    'sort' => '707',
    'from' => 'niba',
    'show' => '泥巴影音',
    'des' => 'www.nbplay.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/niba.html" target="_blank">需要下载泥巴影音播放器</a>',
    'id' => 'niba',
  ),
  'kkhd' => 
  array (
    'status' => '0',
    'sort' => '706',
    'from' => 'kkhd',
    'show' => '可可影音',
    'des' => 'www.kekeplay.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/kkhd.html" target="_blank">需要下载可可影音播放器</a>',
    'id' => 'kkhd',
  ),
  'kankan' => 
  array (
    'status' => '0',
    'sort' => '705',
    'from' => 'kankan',
    'show' => '迅雷看看',
    'des' => 'www.kankan.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/kankan.html" target="_blank">需要下载迅雷看看播放器</a>',
    'id' => 'kankan',
  ),
  'gvod' => 
  array (
    'status' => '0',
    'sort' => '704',
    'from' => 'gvod',
    'show' => '迅播gvod',
    'des' => 'gvod.xunlei.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/gvod.html" target="_blank">需要下载讯播GVOD播放器</a>',
    'id' => 'gvod',
  ),
  'cool' => 
  array (
    'status' => '0',
    'sort' => '703',
    'from' => 'cool',
    'show' => '酷播cool',
    'des' => 'mycoolplay.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/cool.html" target="_blank">需要下载酷播播放器</a>',
    'id' => 'cool',
  ),
  'qvod' => 
  array (
    'status' => '0',
    'sort' => '702',
    'from' => 'qvod',
    'show' => '快播qvod',
    'des' => 'qvod.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/qvod.html" target="_blank">需要下载快播QVOD播放器</a>',
    'id' => 'qvod',
  ),
  'baidu' => 
  array (
    'status' => '0',
    'sort' => '701',
    'from' => 'baidu',
    'show' => '百度影音',
    'des' => 'play.baidu.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/baidu.html" target="_blank">需要下载百度影音播放器</a>',
    'id' => 'baidu',
  ),
  'youku' => 
  array (
    'status' => '0',
    'from' => 'youku',
    'show' => '优酷视频',
    'des' => 'youku.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '618',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  '56_' => 
  array (
    'status' => '0',
    'sort' => '617',
    'from' => '56_',
    'show' => '我乐视频',
    'des' => '56.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => '56_',
  ),
  'tudou' => 
  array (
    'status' => '0',
    'sort' => '616',
    'from' => 'tudou',
    'show' => '土豆视频',
    'des' => 'tudou.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'tudou',
  ),
  'ku6' => 
  array (
    'status' => '0',
    'sort' => '615',
    'from' => 'ku6',
    'show' => '酷6视频',
    'des' => 'ku6.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'ku6',
  ),
  'qq' => 
  array (
    'status' => '0',
    'sort' => '614',
    'from' => 'qq',
    'show' => '腾讯视频',
    'des' => 'v.qq.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'sohu' => 
  array (
    'status' => '0',
    'sort' => '613',
    'from' => 'sohu',
    'show' => '搜狐视频',
    'des' => 'v.sohu.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'joy' => 
  array (
    'status' => '0',
    'sort' => '612',
    'from' => 'joy',
    'show' => '激动网',
    'des' => 'joy.cn',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'joy',
  ),
  'qiyi' => 
  array (
    'status' => '0',
    'sort' => '611',
    'from' => 'qiyi',
    'show' => '奇艺视频',
    'des' => 'qiyi.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'letv' => 
  array (
    'status' => '0',
    'sort' => '610',
    'from' => 'letv',
    'show' => '乐视视频',
    'des' => 'letv.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
  'funshion' => 
  array (
    'status' => '0',
    'sort' => '609',
    'from' => 'funshion',
    'show' => '风行视频',
    'des' => 'funshion.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'funshion',
  ),
  'mgtv' => 
  array (
    'status' => '0',
    'sort' => '608',
    'from' => 'mgtv',
    'show' => '芒果tv',
    'des' => 'mgtv.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'wasu' => 
  array (
    'status' => '0',
    'sort' => '607',
    'from' => 'wasu',
    'show' => '华数tv',
    'des' => 'wasu.cn',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'wasu',
  ),
  'tudouhd' => 
  array (
    'status' => '0',
    'sort' => '606',
    'from' => 'tudouhd',
    'show' => '土豆(高清)',
    'des' => 'hd.tudou.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'tudouhd',
  ),
  'sohuhd' => 
  array (
    'status' => '0',
    'sort' => '605',
    'from' => 'sohuhd',
    'show' => '搜狐(高清)',
    'des' => 'tv.sohu.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'sohuhd',
  ),
  'ku6hd' => 
  array (
    'status' => '0',
    'sort' => '604',
    'from' => 'ku6hd',
    'show' => '酷6(高清)',
    'des' => 'hd.ku6.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'ku6hd',
  ),
  'sinahd' => 
  array (
    'status' => '0',
    'sort' => '603',
    'from' => 'sinahd',
    'show' => '新浪(高清)',
    'des' => 'video.sina.com.cn',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'sinahd',
  ),
  'pptv' => 
  array (
    'status' => '0',
    'sort' => '602',
    'from' => 'pptv',
    'show' => 'pptv',
    'des' => 'pptv.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'fantasy' => 
  array (
    'status' => '0',
    'sort' => '601',
    'from' => 'fantasy',
    'show' => '范特西云视频',
    'des' => '范特西',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'fantasy',
  ),
  'zuidam3u8' => 
  array (
    'status' => '1',
    'from' => 'zuidam3u8',
    'show' => '最大m3u8',
    'des' => 'http://www.zuidazy.net/',
    'ps' => '0',
    'parse' => '',
    'sort' => '551',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'zuidam3u8',
  ),
  'bjm3u8' => 
  array (
    'status' => '1',
    'from' => 'bjm3u8',
    'show' => '极速',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => 'http://zy.bajieziyuan.com/m3u8.php?url=',
    'sort' => '550',
    'tip' => '顶部跑马灯水印',
    'id' => 'bjm3u8',
  ),
  'gqm3u8' => 
  array (
    'status' => '1',
    'from' => 'gqm3u8',
    'show' => '高清在线',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => 'http://111.67.193.41:6065/3.15/?url=',
    'sort' => '549',
    'tip' => '右下角短时出现水印',
    'id' => 'gqm3u8',
  ),
  '605m3u8' => 
  array (
    'status' => '1',
    'from' => '605m3u8',
    'show' => '605在线',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => 'https://www.ppf8.com/605m3u8.php?url=',
    'sort' => '548',
    'tip' => '右下角常驻水印',
    'id' => '605m3u8',
  ),
  'dbm3u8' => 
  array (
    'status' => '0',
    'from' => 'dbm3u8',
    'show' => '豆瓣在线',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => 'https://www.douban888.com/m3u8.php?url=',
    'sort' => '547',
    'tip' => '跑马灯,右下角水印',
    'id' => 'dbm3u8',
  ),
  '172m3u8' => 
  array (
    'status' => '0',
    'from' => '172m3u8',
    'show' => '172在线',
    'des' => '自动连播',
    'ps' => '0',
    'parse' => '',
    'sort' => '531',
    'tip' => '右下角常驻水印',
    'id' => '172m3u8',
  ),
  '172zy' => 
  array (
    'status' => '0',
    'from' => '172zy',
    'show' => '172云播',
    'des' => '自动连播',
    'ps' => '0',
    'parse' => '',
    'sort' => '530',
    'tip' => '右下角常驻水印',
    'id' => '172zy',
  ),
  '35yun' => 
  array (
    'status' => '0',
    'from' => '35yun',
    'show' => '35云播',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '',
    'sort' => '529',
    'tip' => 'https资源',
    'id' => '35yun',
  ),
  '35m3u8' => 
  array (
    'status' => '0',
    'from' => '35m3u8',
    'show' => '35在线',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '',
    'sort' => '528',
    'tip' => 'https资源',
    'id' => '35m3u8',
  ),
  'kuyun' => 
  array (
    'status' => '1',
    'from' => 'kuyun',
    'show' => 'OK在线',
    'des' => 'http://okzyw.com',
    'ps' => '0',
    'parse' => '',
    'sort' => '507',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'kuyun',
  ),
  'ckm3u8' => 
  array (
    'status' => '0',
    'from' => 'ckm3u8',
    'show' => 'ckm3u8',
    'des' => 'http://okzyw.com',
    'ps' => '0',
    'parse' => '',
    'sort' => '506',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'ckm3u8',
  ),
  'kkm3u8' => 
  array (
    'status' => '1',
    'from' => 'kkm3u8',
    'show' => '酷云m3u8',
    'des' => 'http://www.kuyunzy.cc',
    'ps' => '0',
    'parse' => '',
    'sort' => '505',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'kkm3u8',
  ),
  'kkyun' => 
  array (
    'status' => '0',
    'from' => 'kkyun',
    'show' => '酷云播',
    'des' => 'http://www.kuyunzy.cc',
    'ps' => '0',
    'parse' => 'https://www.kuyunjiexi.com/?url=',
    'sort' => '504',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'kkyun',
  ),
  '33uu' => 
  array (
    'status' => '0',
    'from' => '33uu',
    'show' => '33uu',
    'des' => '',
    'ps' => '0',
    'parse' => '',
    'sort' => '502',
    'tip' => '33uu',
    'id' => '33uu',
  ),
  '33uuck' => 
  array (
    'status' => '0',
    'from' => '33uuck',
    'show' => '33uuck',
    'des' => '',
    'ps' => '0',
    'parse' => '',
    'sort' => '501',
    'tip' => '33uuck',
    'id' => '33uuck',
  ),
  'gqyun' => 
  array (
    'status' => '1',
    'from' => 'gqyun',
    'show' => 'gqyun',
    'des' => 'gqyun',
    'ps' => '1',
    'parse' => '',
    'sort' => '99',
    'tip' => 'HD高清',
  ),
);